export interface Todo {
  id: string;
  content: string;
  status: 'pending' | 'in_progress' | 'completed';
  points?: number;
  parentId?: string;  // For hierarchical structure
  depth?: number;     // 0 = epic, 1 = task, 2 = subtask (max)
}

export interface Message {
  role: 'user' | 'assistant';
  content: string;
  // For assistant messages, store the rich step data for rendering
  steps?: AssistantStep[];
}

export interface ToolRun {
  id: string;
  name: string;
  summary: string;
  status: 'running' | 'completed' | 'failed';
}

export interface SubtaskStatus {
  id: string;
  prompt: string;
  status: 'running' | 'completed' | 'failed';
  summary?: string;
}

export interface ContextUsage {
  /** Input tokens (includes system prompt, tools, and all messages) */
  inputTokens: number;
  /** Output tokens generated by the assistant */
  outputTokens: number;
  /** Total tokens (input + output) */
  totalTokens: number;
  /** Percentage of max context window used */
  percentage: number;
  /** Whether usage exceeds warning threshold (32%) */
  warning: boolean;
  /** Whether usage exceeds soft limit (40%) */
  atSoftLimit: boolean;
  /** Model's maximum context window size */
  maxTokens: number;

  // Legacy fields for backwards compatibility
  tokens?: number;
}

export interface Checkpoint {
  id: string;
  timestamp: number;
  name?: string;           // Short description (2-5 words)
  actionSummary?: string;  // Detailed summary for tooltip
}

// IDE-style step types for assistant messages
export type StepType = 'text' | 'tool' | 'subtask';

export interface AssistantStep {
  id: string;
  type: StepType;
  timestamp: number;
  isCollapsed: boolean;

  // For text steps
  content?: string;
  isStreaming?: boolean;

  // For tool steps
  toolName?: string;
  toolInput?: Record<string, unknown>;
  toolOutput?: string;
  toolSummary?: string;
  status?: 'running' | 'completed' | 'failed' | 'pending_approval' | 'stopped';
  filePath?: string;
  processId?: string; // For background processes - links to ProcessManager

  // For subtask steps
  subtaskPrompt?: string;
  subtaskSummary?: string;
}

// Approval flow types
export interface ApprovalRequest {
  requestId: string;
  sessionId: string;
  toolName: string;
  toolInput: Record<string, unknown>;
  summary: string;
  isDangerous: boolean;
  timestamp: number;
  suggestedPattern?: string;
}

export type ApprovalDecision = 'allow_once' | 'allow_pattern' | 'allow_tool' | 'deny';

export interface ApprovalResponse {
  requestId: string;
  decision: ApprovalDecision;
  pattern?: string;
}

// Background process types
export interface BackgroundProcess {
  id: string;
  command: string;
  cwd: string;
  startTime: number;
  output?: string[];
}
